version: '3.1'

# create the network if it does not exist
# docker network create --internal --gateway 172.21.0.1 --subnet 172.21.0.0/16 docker_moac_vnode_network_xchain

services:
  ####################### vnode 1  #######################
  vnodey1:
    image: yifan:vaulty-dev
    ports:
        - "32259:8545"
    command: moac  --networkid 95126 --vnodeconfig vnodeconfig.json --datadir=/vnode --ethash.dagdir /vnode/.ethash --verbosity 3 --rpc --rpcaddr 0.0.0.0 --rpcapi txpool,chain3,mc,net,vnode,personal,admin,miner --ipcpath=/root/.moac/moac.ipc --nodekey /vnode/1.bootnode.key 2>&1
    networks:
      default:
        ipv4_address: 172.21.0.21

  ####################### vnode 2  #######################
  vnodey2:
    image: yifan:vaulty-dev
    ports:
        - "32260:8545"
    command: moac  --networkid 95126 --vnodeconfig vnodeconfig.json --datadir=/vnode --ethash.dagdir /vnode/.ethash --verbosity 3 --rpc --rpcaddr 0.0.0.0 --mine --minerthreads 1 --rpcapi txpool,chain3,mc,net,vnode,personal,admin,miner --ipcpath=/root/.moac/moac.ipc --bootnodesv4 enode://c2d8455aa7b8d0198e36e9f9df71282b2e32122bdf46de3fa218dad900a69ab1289289a67536ea93bfe6e1d7b0044821d0985f2a364e7144c74a5fbeb7e9dc6c@172.21.0.21:30333 --nodekey /vnode/2.bootnode.key 2>&1
    depends_on:
      - vnodey1
    networks:
      default:
        ipv4_address: 172.21.0.22

  ####################### vnode 3  #######################
  vnodey3:
    image: yifan:vaulty-dev
    ports:
        - "32261:8545"
    command: moac  --networkid 95126 --vnodeconfig vnodeconfig.json --datadir=/vnode --ethash.dagdir /vnode/.ethash --verbosity 3 --rpc --rpcaddr 0.0.0.0  --rpcapi txpool,chain3,mc,net,vnode,personal,admin,miner --ipcpath=/root/.moac/moac.ipc --bootnodesv4 enode://c2d8455aa7b8d0198e36e9f9df71282b2e32122bdf46de3fa218dad900a69ab1289289a67536ea93bfe6e1d7b0044821d0985f2a364e7144c74a5fbeb7e9dc6c@172.21.0.21:30333 --nodekey /vnode/3.bootnode.key 2>&1
    depends_on:
      - vnodey1
    networks:
      default:
        ipv4_address: 172.21.0.23

  ####################### vnode 4  #######################
  vnodey4:
    image: yifan:vaulty-dev
    ports:
        - "32262:8545"
    command: moac  --networkid 95126 --vnodeconfig vnodeconfig.json --datadir=/vnode --ethash.dagdir /vnode/.ethash --verbosity 3 --rpc --rpcaddr 0.0.0.0 --rpcapi txpool,chain3,mc,net,vnode,personal,admin,miner --ipcpath=/root/.moac/moac.ipc --bootnodesv4 enode://c2d8455aa7b8d0198e36e9f9df71282b2e32122bdf46de3fa218dad900a69ab1289289a67536ea93bfe6e1d7b0044821d0985f2a364e7144c74a5fbeb7e9dc6c@172.21.0.21:30333 --nodekey /vnode/4.bootnode.key 2>&1
    depends_on:
      - vnodey1
    networks:
      default:
        ipv4_address: 172.21.0.24

  ####################### vnode 5  #######################
  vnodey5:
    image: yifan:vaulty-dev
    ports:
        - "32263:8545"
    command: moac  --networkid 95126 --vnodeconfig vnodeconfig.json --datadir=/vnode --ethash.dagdir /vnode/.ethash --verbosity 3 --rpc --rpcaddr 0.0.0.0 --rpcapi txpool,chain3,mc,net,vnode,personal,admin,miner --ipcpath=/root/.moac/moac.ipc --bootnodesv4 enode://c2d8455aa7b8d0198e36e9f9df71282b2e32122bdf46de3fa218dad900a69ab1289289a67536ea93bfe6e1d7b0044821d0985f2a364e7144c74a5fbeb7e9dc6c@172.21.0.21:30333 --nodekey /vnode/5.bootnode.key 2>&1
    depends_on:
      - vnodey1
    networks:
      default:
        ipv4_address: 172.21.0.25

  ####################### vnode 6  #######################
  vnodey6:
    image: yifan:vaulty-dev
    ports:
        - "32264:8545"
    command: moac  --networkid 95126 --vnodeconfig vnodeconfig.json --datadir=/vnode --ethash.dagdir /vnode/.ethash --verbosity 3 --rpc --rpcaddr 0.0.0.0 --rpcapi txpool,chain3,mc,net,vnode,personal,admin,miner --ipcpath=/root/.moac/moac.ipc --bootnodesv4 enode://c2d8455aa7b8d0198e36e9f9df71282b2e32122bdf46de3fa218dad900a69ab1289289a67536ea93bfe6e1d7b0044821d0985f2a364e7144c74a5fbeb7e9dc6c@172.21.0.21:30333 --nodekey /vnode/6.bootnode.key 2>&1
    depends_on:
      - vnodey1
    networks:
      default:
        ipv4_address: 172.21.0.26

networks:
  default:
    external:
      name: docker_moac_vnode_network_xchain
